#!/usr/bin/env node
// Seed D1 with preseeded messages — one INSERT per --command call
// Usage: node seed-d1.js [--remote]

const { execSync } = require('child_process');

const MESSAGES = [
  { id: "m1", title: "The Whispering Wind of Love", body: "I watched the stars align tonight, but none of them could compare to the light in your eyes. Every heartbeat of mine whispers your name. You are my sanctuary, my anchor, and my beautiful eternity. I never knew love could run this deep until your soul found mine, mapping out a future where every path leads back to you.", relationshipTag: "For Her", occasionTag: "Just Because", tone: "Emotional", keywords: ["touching love messages for her", "heart touching love messages to melt her heart"], length: "Paragraph", slug: "whispering-wind-of-love", likes: 42 },
  { id: "m2", title: "To Make Her Cry Tears of Absolute Joy", body: "If I could give you one gift in this life, it would be the ability to see yourself through my eyes. Only then would you realize how completely breathtaking you are, and how much my world spins around your laughter. You are the poetry I never knew how to write, the song my heart has hummed in silence for years. I am yours, entirely and without condition, for as long as time breathes.", relationshipTag: "For Her", occasionTag: "Just Because", tone: "Emotional", keywords: ["touching love messages for her to make her cry", "long touching love messages for her to make her cry"], length: "Paragraph", slug: "to-make-her-cry-joy", likes: 56 },
  { id: "m3", title: "Across the Silent Miles", body: "Distance is just a test of how far love can travel. Every mile between us is a testament to the strength of our bond. I fall asleep clutching my pillow, pretending it is you, listening to the rhythmic promise of my heart that every tomorrow brings me closer to holding you again. You are my home, no matter how many maps try to separate us.", relationshipTag: "Universal", occasionTag: "Long Distance", tone: "Emotional", keywords: ["long distance love paragraphs", "heart touching love messages for long distance"], length: "Paragraph", slug: "across-silent-miles", likes: 38 },
  { id: "m4", title: "The Silent Anchor of My Life", body: "To the man who holds my world together with his silent strength: you are the calm in my storm, the light in my darkest nights. I look at you and see everything I ever hoped for, wrapped in a laugh that instantly heals my weary heart. Thank you for loving me when I am hard to love, and for holding me so tight that all my broken pieces fit perfectly back together.", relationshipTag: "For Him", occasionTag: "Just Because", tone: "Emotional", keywords: ["heart touching love messages for him", "touching love messages for boyfriend"], length: "Paragraph", slug: "silent-anchor-of-my-life", likes: 33 },
  { id: "m5", title: "Reconciliation and Tears of Healing", body: "I am deeply sorry for the storm I brought into our quiet sanctuary. It breaks my heart to know that my words dimmed the brightness of your smile. Please remember that even when the dark clouds gather, my devotion to you is unwavering. Let us hold hands and heal together, because my life is meaningless without the warmth of your touch.", relationshipTag: "Universal", occasionTag: "Apology", tone: "Sweet", keywords: ["apology love messages", "reconciliation love messages"], length: "Paragraph", slug: "reconciliation-tears-healing", likes: 27 },
  { id: "m6", title: "Sunrise with Your Name Written on My Heart", body: "The morning sun rose with a soft pink blush today, reminding me of the gentle way you woke up yesterday. I write this because my morning feels incomplete without reminding you that you are my first and most beautiful thought of every single day. Have a magical day, my love.", relationshipTag: "For Her", occasionTag: "Good Morning", tone: "Romantic", keywords: ["good morning touching messages for her", "romantic morning messages"], length: "Short SMS", slug: "sunrise-your-name-heart", likes: 61 },
  { id: "m7", title: "A Midnight Promise", body: "As the world falls silent and the moon claims the sky, my thoughts fly straight to you. I wish I was there to whisper sweet dreams into your ear and wrap you in my arms. May the angels watch over you tonight, carrying the warmth of my love straight to your dreams. Sleep well, my beautiful queen.", relationshipTag: "For Her", occasionTag: "Good Night", tone: "Romantic", keywords: ["good night love messages for her", "romantic good night messages"], length: "Short SMS", slug: "midnight-promise", likes: 44 },
  { id: "m8", title: "To My Soulmate on His Special Day", body: "Happy Birthday to the keeper of my keys, the partner of my soul, and the absolute love of my life. Walking beside you is a privilege I thank the heavens for every day. May your year ahead be as incredibly magnificent and compassionate as your beautiful heart is.", relationshipTag: "For Him", occasionTag: "Birthday", tone: "Sweet", keywords: ["birthday love messages for him", "touching birthday messages for boyfriend"], length: "Short SMS", slug: "soulmate-special-day", likes: 29 },
  { id: "m9", title: "A Masterpiece of Love", body: "Dearest, I have spent days trying to find the words to capture what you mean to me, but language feels so limited in the presence of a love this grand. You have painted my grey horizons with the vibrant colours of joy, peace, and unshakeable hope. Before you, I was simply wandering. With you, I have a beautiful purpose. I promise to love you through the quiet afternoons, the turbulent winters, and the golden springs of our lives. You are my masterpiece. Always yours,", relationshipTag: "Universal", occasionTag: "Anniversary", tone: "Passionate", keywords: ["anniversary love letters", "long love messages for anniversary"], length: "Long Letter", slug: "masterpiece-of-love", likes: 72 },
  { id: "m10", title: "The Sound of Your Voice Across Oceans", body: "They tell me long distance is hard, and it is. But when I hear your voice on the phone, the oceans between us evaporate into nothingness. You are my anchor across the tide. I love you more than the miles can ever measure.", relationshipTag: "For Him", occasionTag: "Long Distance", tone: "Emotional", keywords: ["long distance love messages for him", "touching messages for boyfriend far away"], length: "Short SMS", slug: "voice-across-oceans", likes: 19 },
  { id: "m11", title: "A Paragraph of Absolute Devotion", body: "I look at you and realize that God was showing off when He made you. Your kindness heals my doubts, your touch awakens my sleeping soul, and your love gives me a reason to be a better man every single day. I love you, and I will choose you over and over again, without a single doubt.", relationshipTag: "For Her", occasionTag: "Just Because", tone: "Passionate", keywords: ["touching love paragraphs for her", "love paragraphs to make her cry"], length: "Paragraph", slug: "paragraph-absolute-devotion", likes: 88 },
  { id: "m12", title: "The Cry of a Longing Heart", body: "I am writing this with tears in my eyes, not because I am sad, but because I am overwhelmed by how much I miss you. It physically hurts to be away from you, to look at the empty space beside me in bed. But the pain of missing you is a beautiful price to pay for the privilege of loving someone as extraordinary as you.", relationshipTag: "For Him", occasionTag: "I Miss You", tone: "Emotional", keywords: ["i miss you messages for him", "touching messages to make him cry"], length: "Paragraph", slug: "cry-longing-heart", likes: 51 },
  { id: "m13", title: "Valentine from the Depths of My Soul", body: "On this day dedicated to love, I choose you a thousand times over. You are not just my Valentine, you are my every day. You are the warmth in February cold, the flutter in my stomach after all these years, and the reason I believe in beautiful things. Happy Valentine Day, my forever love.", relationshipTag: "Universal", occasionTag: "Valentine's Day", tone: "Romantic", keywords: ["valentines day love messages", "touching valentines day messages"], length: "Paragraph", slug: "valentine-depths-soul", likes: 93 },
  { id: "m14", title: "Thinking of You in Every Quiet Moment", body: "In every quiet moment, in every passing breeze, in the smile of a stranger, I find a reason to think of you. You are embedded in the fabric of my everyday life. I hope you feel how much I think of you, and how grateful I am to have someone worth thinking about so deeply.", relationshipTag: "Universal", occasionTag: "Thinking of You", tone: "Sweet", keywords: ["thinking of you messages", "sweet messages to make her feel special"], length: "Paragraph", slug: "thinking-quiet-moment", likes: 35 },
  { id: "m15", title: "Get Well Soon, My Sunshine", body: "I hate seeing you unwell. It makes my heart ache in ways I cannot describe. Please rest, drink warm things, and know that every minute you feel sick, I am sending all my love your way. Get well soon, because the world is infinitely better when you are smiling in it.", relationshipTag: "Universal", occasionTag: "Get Well Soon", tone: "Comforting", keywords: ["get well soon messages", "comforting love messages for sick partner"], length: "Short SMS", slug: "get-well-soon-sunshine", likes: 16 },
  { id: "m16", title: "An Instagram Caption Straight from the Heart", body: "Not every love story makes headlines, but ours makes my heart skip every single time. Here is to the one who makes ordinary days feel like the most extraordinary adventure. You are my favorite notification.", relationshipTag: "Universal", occasionTag: "Instagram Captions", tone: "Sweet", keywords: ["instagram captions for love", "cute instagram captions for boyfriend girlfriend"], length: "Short SMS", slug: "instagram-caption-heart", likes: 104 },
  { id: "m17", title: "The Anniversary of Our Beautiful Beginning", body: "Another year around the sun with you, and I am still the most grateful person alive. Every chapter we have written together is my absolute favorite. Here is to a thousand more years of laughing too loud, crying at movies, and building this extraordinary life side by side. I love you, today and every day.", relationshipTag: "Universal", occasionTag: "Anniversary", tone: "Romantic", keywords: ["anniversary messages", "touching anniversary messages for partner"], length: "Paragraph", slug: "anniversary-beautiful-beginning", likes: 67 },
  { id: "m18", title: "Congratulations, My Greatest Champion", body: "Everything you have achieved fills me with a pride that words can barely hold. You worked for this, you dreamed of this, and now you have it. I have watched you pour your heart into every single step, and I am so honored to be the one standing beside you as you celebrate. Congratulations, my love. You deserve every good thing.", relationshipTag: "Universal", occasionTag: "Congratulations", tone: "Sweet", keywords: ["congratulations messages for partner", "proud of you love messages"], length: "Paragraph", slug: "congratulations-greatest-champion", likes: 22 },
  { id: "m19", title: "The Weight of Missing You", body: "Missing you is not just a feeling, it is a physical ache, a hollow in my chest where you usually live. I am counting every second until I can hold your face in my hands again and tell you in person what my words can barely capture: I love you, and I am so incomplete without you.", relationshipTag: "Universal", occasionTag: "I Miss You", tone: "Emotional", keywords: ["i miss you love messages", "emotional missing you messages"], length: "Paragraph", slug: "weight-missing-you", likes: 47 },
  { id: "m20", title: "Good Morning to My Reason for Everything", body: "Before the coffee, before the news, before the world demands anything from me, there is you. A quiet, warm thought of you that starts my every morning like gentle sunlight through a window. Good morning to the one who makes waking up worth it.", relationshipTag: "Universal", occasionTag: "Good Morning", tone: "Romantic", keywords: ["good morning love messages", "romantic good morning messages for partner"], length: "Short SMS", slug: "good-morning-reason-everything", likes: 79 },
  { id: "m21", title: "A Good Night That Feels Like a Poem", body: "The stars are out tonight, and I keep searching for the brightest one, only to realize it could never outshine you. Goodnight, my love. May your sleep be deep, your dreams be vivid, and may you wake up tomorrow knowing you are my absolute world.", relationshipTag: "Universal", occasionTag: "Good Night", tone: "Romantic", keywords: ["good night love messages", "poetic good night messages for partner"], length: "Short SMS", slug: "good-night-feels-poem", likes: 58 },
  { id: "m22", title: "A Birthday Wish Wrapped in Forever", body: "Happy Birthday, my love. Today, I celebrate not just the day you were born, but every single moment your existence has graced my life. You are the best gift I never knew I needed. May today and every day ahead be as magical and extraordinary as you are.", relationshipTag: "Universal", occasionTag: "Birthday", tone: "Sweet", keywords: ["birthday love messages", "happy birthday romantic messages for partner"], length: "Short SMS", slug: "birthday-wish-wrapped-forever", likes: 41 },
  { id: "m23", title: "The Apology My Heart Could Not Hold Back", body: "I am sorry. Not because I have to be, but because knowing I hurt you is the most unbearable feeling in the world. You mean everything to me, and protecting your heart is something I should have done better. Please know that every part of me is committed to doing better, to loving you louder, and to never letting pride stand between us again.", relationshipTag: "Universal", occasionTag: "Apology", tone: "Emotional", keywords: ["apology love messages", "i am sorry messages for partner"], length: "Paragraph", slug: "apology-heart-couldnt-hold-back", likes: 63 },
  { id: "m24", title: "Reconciliation, Let Us Begin Again", body: "Arguments are a storm we have to pass through, not a wall that separates us forever. I choose us, even after the hard moments. Especially after the hard moments. Let us begin again, with softer words, open hearts, and the unshakeable knowledge that what we have is worth every effort.", relationshipTag: "Universal", occasionTag: "Reconciliation After an Argument", tone: "Comforting", keywords: ["reconciliation messages", "making up after argument love messages"], length: "Paragraph", slug: "reconciliation-begin-again", likes: 39 }
];

const remote = process.argv.includes('--remote');
const flag = remote ? '--remote' : '--local';

function esc(s) { return String(s).replace(/'/g, "''"); }

let ok = 0, fail = 0;
for (const m of MESSAGES) {
  const sql = `INSERT OR IGNORE INTO Message (id,title,body,relationshipTag,occasionTag,tone,keywords,length,slug,likes) VALUES ('${esc(m.id)}','${esc(m.title)}','${esc(m.body)}','${esc(m.relationshipTag)}','${esc(m.occasionTag)}','${esc(m.tone)}','${esc(JSON.stringify(m.keywords))}','${esc(m.length||'')}','${esc(m.slug)}',${m.likes});`;
  try {
    execSync(`npx wrangler d1 execute touching-messages-db ${flag} --command "${sql.replace(/"/g, '\\"')}"`, { cwd: process.cwd(), stdio: 'pipe' });
    process.stdout.write('.');
    ok++;
  } catch (e) {
    console.error(`\n❌ Failed ${m.id}: ${e.message.substring(0, 200)}`);
    fail++;
  }
}
console.log(`\n✅ ${ok} inserted, ${fail} failed`);
